name: flutter_map_marker_cluster
description: A Dart implementation of Leaflet.makercluster for Flutter apps.
  Provides beautiful animated marker clustering functionality for flutter_map.
version: 1.4.0

homepage: https://github.com/lpongetti/flutter_map_marker_cluster

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map:
    git: https://github.com/translibrius/flutter_map_trackpadfix
  flutter_map_marker_popup: ^7.0.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
